language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: f0VU0gjL1+2o+KLNho/M/RHiAHyOziEAxg4+uCtfJMzEEOfvsz8cN3dCKx/SvVCPuew/e1PFPxLfAvk+lms5Bs1+/iUmqGaNOEeFJe5tNrvqXsjLQBF8RQ65PGbMLaO+cq8W7iMHdbnS8y+2u5kWksO/2zk/lZKxrmva4m+XMxg6BeFdZ0SMe0XffM5MP9CkviJpjTpHszv4tQ7l74/AxRkkUF6gz1AGrDbhHRYMxNKdDnMXSgaTvRzAlVLxb4xknd69uZvAErbWy6LRF5YV5Etk47L04016Qm7bKn2rBTqJqBYwGLcErpbB+gXVyEXSY7CigszlwCxJF5I6nugSOV02qAEuyN04/pXFOuiPaJJ9fWdNTkr/t6CKU2VEsk0q0mVE9zApTrzEwRIxjuvDhZrhjtOnYvfI7XrASumX0Hxa/+aiHB9A19YmW9ZQBg3xxuUAc9JHj01iRZQyuN6TberImhp69Kz9WwCp6/2r8msEIGvq31ku1EuwahGxp2nVuk3tUjSRIybjcdUvxnJEHNi4NIt3P9d//ZH13G95CSsYDVcCXhK646PkSSY8720HyucZ5bCtVl5+DQIlmvGWIQB6yVieac51cX2n4Q5JK3dI499BHEEcTK4i9xsKaaTm6tudYsmic7jcA+Nk5jfT4H7HlAVjXpr8lLl46+rx0lE=
  app: 
  on:
    branch: main
  run: rails db:migrate
