language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: CNAbgynA7pTOWrEcXmv5PaYfE3Y0HKalB0x3STh8mGXwWheBm6vF292kaYQ6Y8w5sx4H6WiykyGnttYYStCTbdw8pkwx52pCjnRqEnTSLuYK8UcD9SHMz7mnKTpt5nudI2/DpUSS83Wn0WnzDGPWfuZJT6b7owYhKIc/cFZLQPm5viAmIVAkmpCsNxWh25mXG4N4aTrGOaqfC+4NKWTfWm3Pw+IM1y05banQPIYnsVVLCDSEC6vtSImgzye8VjWx+xLyuJPFlJc0CN+Pgfx8e7xPZ8lgta01GLE4w/Zvxmg2Mmu4w+xb4f/Z3NBerv+wGg1DGaESyEg2BC2v1bdrBl9SwWHwicRSEW2cBEoRFl5ALulizddd7fCbWClpegCzDPDaoe3VTBJAFmdxzP2kL9xtat94DwX94tk6i5XXGSvHUaFrdFiDOQw9rUf6CEoYIJ2wg5dDHV1OtncKFgqk11gdz2Q8g6pPDvZg+kGpqenh3UhBVJxDl799IiNEWS/9XldB4SVKW8iE4LMPgHHq3NrH4wIQwYHl5hUeoxLVTgDJ67nxDJ6+6A8sEzweCzwzA50sI+IYlYtlkgiL6P1UUC3zzMsX0XoUN8Kwazfw3WVhkUKPKsCRwUoGbGyBtwWeHlSFciU0Kc4m4D/CfQvhVB+tM8Kt/VIgCjfJfssTAQM=
  app: potato-viewing-party
  on:
    branch: main
  run: rails db:migrate
env:
  global:
    - API_KEY: "5cd82cd9b942d566b653cf04d3440211"
